-- MySQL Script generated by MySQL Workbench
-- Tue Oct 31 00:21:54 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fruitmart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fruitmart` ;

-- -----------------------------------------------------
-- Schema fruitmart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fruitmart` DEFAULT CHARACTER SET utf8 ;
USE `fruitmart` ;

-- -----------------------------------------------------
-- Table `fruitmart`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`customer` ;

CREATE TABLE IF NOT EXISTS `fruitmart`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index2` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruitmart`.`fruit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`fruit` ;

CREATE TABLE IF NOT EXISTS `fruitmart`.`fruit` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `image_uri` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fruit_name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruitmart`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`order` ;

CREATE TABLE IF NOT EXISTS `fruitmart`.`order` (
  `id` INT(11) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `comments` VARCHAR(45) NULL DEFAULT NULL,
  `total_cost` FLOAT NOT NULL,
  `customer_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `customer_id`),
  INDEX `fk_orders_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_orders_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `fruitmart`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruitmart`.`shopping_cart_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`shopping_cart_items` ;

CREATE TABLE IF NOT EXISTS `fruitmart`.`shopping_cart_items` (
  `id` INT(11) NOT NULL,
  `selected_quantity` INT NOT NULL,
  `cost` FLOAT NOT NULL,
  `orders_id` INT(11) NOT NULL,
  `fruit_id` INT(11) NOT NULL,
  INDEX `fk_shopping_cart_orders1_idx` (`orders_id` ASC),
  INDEX `fk_shopping_cart_items_fruit1_idx` (`fruit_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shopping_cart_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `fruitmart`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_cart_items_fruit1`
    FOREIGN KEY (`fruit_id`)
    REFERENCES `fruitmart`.`fruit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
