-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 01:42:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema fruitmart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fruitmart` ;

-- -----------------------------------------------------
-- Schema fruitmart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fruitmart` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `fruitmart` ;

-- -----------------------------------------------------
-- Table `fruitmart`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `index2` ON `fruitmart`.`customer` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fruitmart`.`fruit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`fruit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`fruit` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `image_uri` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `fruit_name_UNIQUE` ON `fruitmart`.`fruit` (`name` ASC);
-- -----------------------------------------------------
-- inserts for fruits
-- -----------------------------------------------------
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Acorns',1.5,'1 kg of Acorns','resources/images/acorn_squash.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Apples',2,'1 kg of Apples','resources/images/apple.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Bell Peppers',2.8,'1 kg of Bell Pepper','resources/images/bell_pepper.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Blue Berries',3.6,'1 kg of Blue Berry','resources/images/blueberries.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Broccoli',1.9,'1 kg of Broccoli','resources/images/broccoli.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Carrots',1.3,'1 kg of Carrots','resources/images/carrot.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Celery',2,'1 packet of Celery','resources/images/celery.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Chili Peppers',1.5,'1 packet of Chili peppers','resources/images/chili_pepper.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Corn',2.4,'1 packet of Corn','resources/images/corn.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Egg Plant',1.6,'1 kg of Egg Plant','resources/images/eggplant.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Lettuce',1.4,'1 kg of lettuce','resources/images/lettuce.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Mushrooms',3,'1 packet of Mushrooms','resources/images/mushroom.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Onions',3.6,'1 kg of Onions','resources/images/onion.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Potatos',2,'1 kg of Pototoes','resources/images/potato.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Pumpkins',3.4,'1 kg of Pumpkin','resources/images/pumpkin.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Radishes',2,'1 packet of Radishes','resources/images/radish.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Squash',3,'1 kg of squash','resources/images/squash.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Strawberries',3.6,'1 packet of Strawberries','resources/images/strawberry.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Peas',2.6,'1 packet of Peas','resources/images/sugar_snap.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Tomatoes',2.5,'1 kg of Tomotoes','resources/images/tomato.png');
insert into fruitmart.fruit(`name`,`price`,`description`,`image_uri`) values ('Zucchinis',1.6,'1 kg of Zucchinis','resources/images/zucchini.png');
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fruitmart`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`order` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NOT NULL,
  `comments` VARCHAR(1000) NULL DEFAULT NULL,
  `total_cost` FLOAT NOT NULL,
  `customer_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `fruitmart`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_order_customer1_idx` ON `fruitmart`.`order` (`customer_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fruitmart`.`shopping_cart_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`shopping_cart_items` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`shopping_cart_items` (
  `id` INT(11) NOT NULL,
  `selected_quantity` INT NOT NULL,
  `cost` FLOAT NOT NULL,
  `order_id` INT(11) NOT NULL,
  `fruit_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shopping_cart_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `fruitmart`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_cart_items_fruit1`
    FOREIGN KEY (`fruit_id`)
    REFERENCES `fruitmart`.`fruit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_shopping_cart_items_fruit1_idx` ON `fruitmart`.`shopping_cart_items` (`fruit_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_shopping_cart_items_order1_idx` ON `fruitmart`.`shopping_cart_items` (`order_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
