-- MySQL Script generated by MySQL Workbench
-- Wed Nov  1 19:38:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fruitmart_warehouse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fruitmart_warehouse` ;

-- -----------------------------------------------------
-- Schema fruitmart_warehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fruitmart_warehouse` DEFAULT CHARACTER SET utf8 ;
USE `fruitmart_warehouse` ;

-- -----------------------------------------------------
-- Table `fruitmart_warehouse`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart_warehouse`.`orders` ;

CREATE TABLE IF NOT EXISTS `fruitmart_warehouse`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cust_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NULL,
  `comment` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fruitmart_warehouse`.`cart_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart_warehouse`.`cart_items` ;

CREATE TABLE IF NOT EXISTS `fruitmart_warehouse`.`cart_items` (
  `item_name` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `orders_id` INT(11) NOT NULL,
  CONSTRAINT `fk_cart_items_orders`
    FOREIGN KEY (`orders_id`)
    REFERENCES `fruitmart_warehouse`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
