-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 19:24:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema fruitmart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fruitmart` ;

-- -----------------------------------------------------
-- Schema fruitmart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fruitmart` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `fruitmart` ;

-- -----------------------------------------------------
-- Table `fruitmart`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`customer` (
  `customer_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `index2` ON `fruitmart`.`customer` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fruitmart`.`fruit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`fruit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`fruit` (
  `fruit_id` INT(11) NOT NULL,
  `fruit_name` VARCHAR(45) NULL DEFAULT NULL,
  `desc` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`fruit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `fruit_name_UNIQUE` ON `fruitmart`.`fruit` (`fruit_name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fruitmart`.`fruit_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`fruit_cart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`fruit_cart` (
  `fruit_id` INT(11) NOT NULL,
  `shoppingcart_id` INT(11) NOT NULL,
  PRIMARY KEY (`fruit_id`, `shoppingcart_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fruitmart`.`shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`shopping_cart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`shopping_cart` (
  `id` INT(11) NOT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `customer_id` INT(11) NULL DEFAULT NULL,
  `comments` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
