-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 19:24:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema fruitmart
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fruitmart` ;

-- -----------------------------------------------------
-- Schema fruitmart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fruitmart` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `fruitmart` ;

-- -----------------------------------------------------
-- Table `fruitmart`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `index2` ON `fruitmart`.`customer` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fruitmart`.`fruit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`fruit` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`fruit` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `quantity` int NULL DEFAULT NULL,
  `price` float NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `image_uri` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `fruit_name_UNIQUE` ON `fruitmart`.`fruit` (`name` ASC);
-- -----------------------------------------------------
-- inserts for fruits
-- -----------------------------------------------------
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Acorns',50,1.5,'1 kg of Acorns','resources/images/acorn_squash.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Apples',40,2,'1 kg of Apples','resources/images/apple.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Bell Peppers',60,2.8,'1 kg of Bell Pepper','resources/images/bell_pepper.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Blue Berries',30,3.6,'1 kg of Blue Berry','resources/images/blueberries.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Broccoli',50,1.9,'1 kg of Broccoli','resources/images/broccoli.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Carrots',70,1.3,'1 kg of Carrots','resources/images/carrot.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Celery',40,2,'1 packet of Celery','resources/images/celery.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Chili Peppers',100,1.5,'1 packet of Chili peppers','resources/images/chili_pepper.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Corn',90,2.4,'1 packet of Corn','resources/images/corn.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Egg Plant',80,1.6,'1 kg of Egg Plant','resources/images/eggplant.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Lettuce',40,1.4,'1 kg of lettuce','resources/images/lettuce.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Mushrooms',80,3,'1 packet of Mushrooms','resources/images/mushroom.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Onions',70,3.6,'1 kg of Onions','resources/images/onion.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Potatos',90,2,'1 kg of Pototoes','resources/images/potato.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Pumpkins',40,3.4,'1 kg of Pumpkin','resources/images/pumpkin.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Radishes',60,2,'1 packet of Radishes','resources/images/radish.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Squash',70,3,'1 kg of squash','resources/images/squash.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Strawberries',30,3.6,'1 packet of Strawberries','resources/images/strawberry.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Peas',80,2.6,'1 packet of Peas','resources/images/sugar_snap.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Tomatoes',75,2.5,'1 kg of Tomotoes','resources/images/tomato.png');
insert into fruitmart.fruit(`name`,`quantity`,`price`,`description`,`image_uri`) values ('Zucchinis',65,1.6,'1 kg of Zucchinis','resources/images/zucchini.png');
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fruitmart`.`fruit_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`fruit_cart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`fruit_cart` (
  `fruit_id` INT(11) NOT NULL,
  `shoppingcart_id` INT(11) NOT NULL,
  PRIMARY KEY (`fruit_id`, `shoppingcart_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `fruitmart`.`shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruitmart`.`shopping_cart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `fruitmart`.`shopping_cart` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_date` DATETIME NULL DEFAULT NULL,
  `customer_id` INT(11) NULL DEFAULT NULL,
  `comments` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
